I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scenes/script.rpy", line 16, in script call
    call act1a from _call_act1a
  File "game/scenes/act1a.rpy", line 35, in script
    u "You’re quite a cutie, gettin’ scared like that."
Exception: Sayer 'u' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scenes/script.rpy", line 16, in script call
    call act1a from _call_act1a
  File "game/scenes/act1a.rpy", line 35, in script
    u "You’re quite a cutie, gettin’ scared like that."
  File "C:\Users\kasey\renpy-8.1.1-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\kasey\renpy-8.1.1-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'u' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.1.23060707
Snake Bitten 1.0
Sun Oct 15 16:39:58 2023
